### ISSUE TITLE
一些loopr2细节建议

### ISSUE THREAD

**Issue by tianheng2017** [LoopringSecondary/loopr#134]
![qq20180322-162839](https://user-images.githubusercontent.com/29515610/37759427-8e562b62-2dee-11e8-8db3-9b04ab0c4db4.png)
1、这个“高级选项”是不是对普通用户有点太难理解了，建议在“Lrc 手续费”和“分润比例”旁边加一个问号图标，鼠标滑上去会弹出相关解释，解释设置与不设置的区别，还有这两个输入框应该有一个范围参考值。
2、“有效时间”选中后只是边框变色不够明显，建议改为按钮背景蓝色，按钮文字白色
3、首页（/home）中间就一行文字，背景纯白色，感觉挺空的，如果能加个关于区块链的背景图就好了
4、投资组合页面（/wallet/portfolio），饼图padding-top: 5rem !important看起来挺不协调的，改成2rem，上下协调，刚刚好
5、"高级选项"里面的输入框，鼠标滑过也应该有边框变色反馈，不一定要获取焦点后才有，同时选择数量那个滑动条左边的小圆点也应该有颜色，参考okex

**Comment by dyfvicture** [comment]
会有的，在和设计师沟通
