### ISSUE TITLE
UX Suggestion

### ISSUE THREAD

**Issue by hzbdesigner** [LoopringSecondary/loopr#142]
#### 信息困惑有哪些?
- lrcFee
- marginSpilit分润
- 订单 Gas

#### 流程困惑有哪些?
- transfer  again
- convert again
- 每一个modal的提交和取消（关闭之后）的页面跳转
- 每一个form提交之后的，结果反馈

#### 操作便捷性问题
- 回车直接提交

#### 其他
- todo

#### fay的疑问

- 面向的用户
   -  1%的用户，可能知道去中心化交易，但是不知道去中心化的交易所的原理和概念
   -  WETH , LRC Fee, 分润，ttl, OrderGas
- 进入首页：不知道这个产品是什么？能解决我什么问题？有什么优势？
    - 是产品还是交易所？准备给用户传达什么？
    -  建议：对标用户熟悉的交易所，描述
- 进入交易页：不知道这个页面是干什么的，不知道我能做什么？
    - markets list 隐藏很深
    - 三个交易所的信息：用户不知道那些是什么的？需要猜？需要展示 币安
      - 多个交易所的信息的信息 蓝色和白色，被设计区分开来，以为不是一个东西
    - 两个 form 太大，占据太多区块，同时
- 备份的提示：版式很难看
- WETH

**Comment by dyfvicture** [comment]
1.
 ![wechatimg1066](https://user-images.githubusercontent.com/6755466/37810632-26a79224-2e90-11e8-83b6-d99450b580ab.jpeg)
修改背景颜色，突出下拉

2.
![wechatimg1069](https://user-images.githubusercontent.com/6755466/37810644-4b716422-2e90-11e8-9cb7-5679e2d686fe.jpeg)
调整间距，行铺满

**Comment by dyfvicture** [comment]
![image](https://user-images.githubusercontent.com/6755466/37810717-b73ab050-2e90-11e8-9901-a8bca9be251e.png)
下单失败时，进一步提示，lrc为什么不足，eth不足有那几部分，可以考虑用下拉框展示details？

**Comment by dyfvicture** [comment]
![image](https://user-images.githubusercontent.com/6755466/37811138-393b9b6c-2e93-11e8-804a-d351469b49d8.png)
所有字体，大小，包括placeholder里显示的字体
